
# Data Files
training_data: train_ver2.csv
test_data: test_ver2.csv


# Model
model_file_name: svd_model_v


# Encoders
user_encoder: user_encoder_v
service_encoder: service_encoder_v

# Variables
feature_dict:
  ind_ahor_fin_ult1: 0
  ind_aval_fin_ult1: 1
  ind_cco_fin_ult1: 2
  ind_cder_fin_ult1: 3
  ind_cno_fin_ult1: 4
  ind_ctju_fin_ult1: 5
  ind_ctma_fin_ult1: 6
  ind_ctop_fin_ult1: 7
  ind_ctpp_fin_ult1: 8
  ind_deco_fin_ult1: 9
  ind_dela_fin_ult1: 10
  ind_deme_fin_ult1: 11
  ind_ecue_fin_ult1: 12
  ind_fond_fin_ult1: 13
  ind_hip_fin_ult1: 14
  ind_nom_pens_ult1: 15
  ind_nomina_ult1: 16
  ind_plan_fin_ult1: 17
  ind_pres_fin_ult1: 18
  ind_reca_fin_ult1: 19
  ind_recibo_ult1: 20
  ind_tjcr_fin_ult1: 21
  ind_valo_fin_ult1: 22
  ind_viv_fin_ult1: 23

n_epochs: 10

lr_all: 0.005

reg_all: 0.6

engineered_variable_1: service_selection_ratio

engineered_variable_2: service_opted